---
- name: APT Proxy Konfiguration
  hosts: proxmox_all_lxc:&proxmox_all_running
  become: true

  vars:
    # Standard Proxy URL (ohne /acng-report.html)
    apt_proxy_url: "http://10.0.200.108:3142"

  tasks:
    - name: APT Proxy konfigurieren (/etc/apt/apt.conf.d/01proxy)
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        content: |
          Acquire::http::Proxy "{{ apt_proxy_url }}";
        owner: root
        group: root
        mode: '0644'
